### ISSUE TITLE
Services API

### ISSUE THREAD

**Issue by bobrot** [danesparza/consul-api#1]
There doesn't seem to be any way to pull down service information. IMHO, the key/value stuff is pretty minor compared to what Consul is meant to do. Will there be an integration to get a service definition?

**Comment by danesparza** [comment]
What would you like it to look like?

**Comment by bobrot** [comment]
I actually had to roll my own implementation with the Web API client library due to the dependency on Service Stack. At any rate, thanks for being so responsive on this.
